name: Build and Deploy Site

on:
  push:
    branches:
      - master
  pull_request:
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive # This option recursively checks out submodules

      - name: Install Zola
        run: |
          curl -sL https://github.com/getzola/zola/releases/latest/download/zola-v0.21.0-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv zola /usr/local/bin/zola

      - name: Build site
        run: zola build

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: public

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: public
